<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sanjay-PC" name="com.koovs.testngscripts.SceneriosTest" tests="2" failures="1" timestamp="26 Nov 2015 06:25:00 GMT" time="28.087" errors="0">
  <testcase name="ProductSelectionTestforMen" time="15.350" classname="com.koovs.testngscripts.SceneriosTest">
    <failure type="org.sikuli.script.FindFailed" message="can not find P(E:\Images\MenProductForwardArrow.PNG) S: 0.7 on the screen.">
      <![CDATA[FindFailed: can not find P(E:\Images\MenProductForwardArrow.PNG) S: 0.7 on the screen.
  Line 1574, in file Region.java

	at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
	at org.sikuli.script.Region.wait(Region.java:1682)
	at org.sikuli.script.Region.find(Region.java:1590)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:1991)
	at org.sikuli.script.Region.click(Region.java:2197)
	at org.sikuli.script.Region.click(Region.java:2181)
	at com.koovs.businesslib.DynamicBannerHandling.sikuliImageCompare(DynamicBannerHandling.java:79)
	at com.koovs.testngscripts.SceneriosTest.ProductSelectionTestforMen(SceneriosTest.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- ProductSelectionTestforMen -->
  <testcase name="logintest" time="12.737" classname="com.koovs.testngscripts.SceneriosTest"/>
</testsuite> <!-- com.koovs.testngscripts.SceneriosTest -->
